name: Development
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.1
        with:
          provider: aws # default is linode
          region: "us-east-1"
          access_key: dev
          secret_key: Sobral123.
      - name: Interact with object storage
        run: |
          s3cmd --no-ssl --access_key=hugo --secret_key=Sobral123. --host-bucket=s3.dev.hugoprado.me --host s3.dev.hugoprado.me sync --recursive --progress assets s3://dev.hugoprado.me
          s3cmd --no-ssl --access_key=hugo --secret_key=Sobral123. --host-bucket=s3.dev.hugoprado.me --host s3.dev.hugoprado.me sync --recursive --progress images s3://dev.hugoprado.me
          s3cmd --no-ssl --access_key=hugo --secret_key=Sobral123. --host-bucket=s3.dev.hugoprado.me --host s3.dev.hugoprado.me put index.html s3://dev.hugoprado.me
